### ISSUE TITLE
Add Message interface to rcljava_common

### ISSUE THREAD

**Issue by Theosakamg** [esteve/ros2_java#7]
For protect the design, I add Message interface 

https://github.com/Theosakamg/ros2_java/tree/ros2_alpha7/rosidl_generator_java/src/main/java/org/ros2/internal/message
https://github.com/Theosakamg/ros2_java/blob/ros2_alpha7/rosidl_generator_java/resource/msg.java.template

**Comment by esteve** [comment]
Please do not use OSRF's copyright notice, it may mislead people to think this is an OSRF approved project. Also, I don't use the "@author" tag because it's hard to maintain, I prefer keeping a list of all the contributors (see https://github.com/esteve/ros2_java/blob/master/THANKS). The Apache Software Foundation removed the "@author" tag both for pragmatic and philosophical reasons, as it creates an imbalance in how communities build software.

In any case, the aim of this project is to mimic `rclcpp`, which does not use interfaces for messages. Could you open a pull request so we can discuss these changes? Thanks.
